Shader "lilToon/lilSSAO/lilToon" {
	Properties {
		_DummyProperty ("", Float) = 0
		_DummyProperty ("", Float) = 0
		_DummyProperty ("", Float) = 0
		_DummyProperty ("", Float) = 0
		_DummyProperty ("", Float) = 0
		_DummyProperty ("", Float) = 0
		_DummyProperty ("", Float) = 0
		[Space(1000)] _DummyProperty ("", Float) = 0
		_Invisible ("", Float) = 0
		_AsUnlit ("", Range(0, 1)) = 0
		_Cutoff ("", Range(-0.001, 1.001)) = 0.5
		_SubpassCutoff ("", Range(0, 1)) = 0.5
		_FlipNormal ("", Float) = 0
		_ShiftBackfaceUV ("", Float) = 0
		_BackfaceForceShadow ("", Range(0, 1)) = 0
		_BackfaceColor ("", Vector) = (0,0,0,0)
		_VertexLightStrength ("", Range(0, 1)) = 0
		_LightMinLimit ("", Range(0, 1)) = 0.05
		_LightMaxLimit ("", Range(0, 10)) = 1
		_BeforeExposureLimit ("", Float) = 10000
		_MonochromeLighting ("", Range(0, 1)) = 0
		_AlphaBoostFA ("", Range(1, 100)) = 10
		_lilDirectionalLightStrength ("", Range(0, 1)) = 1
		_LightDirectionOverride ("", Vector) = (0.001,0.002,0.001,0)
		_AAStrength ("", Range(0, 1)) = 1
		_UseDither ("", Float) = 0
		_DitherTex ("", 2D) = "white" {}
		_DitherMaxValue ("", Float) = 255
		_EnvRimBorder ("", Range(0, 3)) = 3
		_EnvRimBlur ("", Range(0, 1)) = 0.35
		_Color ("", Vector) = (1,1,1,1)
		_MainTex ("", 2D) = "white" {}
		_MainTex_ScrollRotate ("", Vector) = (0,0,0,0)
		_MainTexHSVG ("", Vector) = (0,1,1,1)
		_MainGradationStrength ("", Range(0, 1)) = 0
		_MainGradationTex ("", 2D) = "white" {}
		_MainColorAdjustMask ("", 2D) = "white" {}
		_UseMain2ndTex ("", Float) = 0
		_Color2nd ("", Vector) = (1,1,1,1)
		_Main2ndTex ("", 2D) = "white" {}
		_Main2ndTexAngle ("", Float) = 0
		_Main2ndTex_ScrollRotate ("", Vector) = (0,0,0,0)
		_Main2ndTex_UVMode ("", Float) = 0
		_Main2ndTex_Cull ("", Float) = 0
		_Main2ndTexDecalAnimation ("", Vector) = (1,1,1,30)
		_Main2ndTexDecalSubParam ("", Vector) = (1,1,0,1)
		_Main2ndTexIsDecal ("", Float) = 0
		_Main2ndTexIsLeftOnly ("", Float) = 0
		_Main2ndTexIsRightOnly ("", Float) = 0
		_Main2ndTexShouldCopy ("", Float) = 0
		_Main2ndTexShouldFlipMirror ("", Float) = 0
		_Main2ndTexShouldFlipCopy ("", Float) = 0
		_Main2ndTexIsMSDF ("", Float) = 0
		_Main2ndBlendMask ("", 2D) = "white" {}
		_Main2ndTexBlendMode ("", Float) = 0
		_Main2ndTexAlphaMode ("", Float) = 0
		_Main2ndEnableLighting ("", Range(0, 1)) = 1
		_Main2ndDissolveMask ("", 2D) = "white" {}
		_Main2ndDissolveNoiseMask ("", 2D) = "gray" {}
		_Main2ndDissolveNoiseMask_ScrollRotate ("", Vector) = (0,0,0,0)
		_Main2ndDissolveNoiseStrength ("", Float) = 0.1
		_Main2ndDissolveColor ("", Vector) = (1,1,1,1)
		_Main2ndDissolveParams ("", Vector) = (0,0,0.5,0.1)
		_Main2ndDissolvePos ("", Vector) = (0,0,0,0)
		_Main2ndDistanceFade ("", Vector) = (0.1,0.01,0,0)
		_UseMain3rdTex ("", Float) = 0
		_Color3rd ("", Vector) = (1,1,1,1)
		_Main3rdTex ("", 2D) = "white" {}
		_Main3rdTexAngle ("", Float) = 0
		_Main3rdTex_ScrollRotate ("", Vector) = (0,0,0,0)
		_Main3rdTex_UVMode ("", Float) = 0
		_Main3rdTex_Cull ("", Float) = 0
		_Main3rdTexDecalAnimation ("", Vector) = (1,1,1,30)
		_Main3rdTexDecalSubParam ("", Vector) = (1,1,0,1)
		_Main3rdTexIsDecal ("", Float) = 0
		_Main3rdTexIsLeftOnly ("", Float) = 0
		_Main3rdTexIsRightOnly ("", Float) = 0
		_Main3rdTexShouldCopy ("", Float) = 0
		_Main3rdTexShouldFlipMirror ("", Float) = 0
		_Main3rdTexShouldFlipCopy ("", Float) = 0
		_Main3rdTexIsMSDF ("", Float) = 0
		_Main3rdBlendMask ("", 2D) = "white" {}
		_Main3rdTexBlendMode ("", Float) = 0
		_Main3rdTexAlphaMode ("", Float) = 0
		_Main3rdEnableLighting ("", Range(0, 1)) = 1
		_Main3rdDissolveMask ("", 2D) = "white" {}
		_Main3rdDissolveNoiseMask ("", 2D) = "gray" {}
		_Main3rdDissolveNoiseMask_ScrollRotate ("", Vector) = (0,0,0,0)
		_Main3rdDissolveNoiseStrength ("", Float) = 0.1
		_Main3rdDissolveColor ("", Vector) = (1,1,1,1)
		_Main3rdDissolveParams ("", Vector) = (0,0,0.5,0.1)
		_Main3rdDissolvePos ("", Vector) = (0,0,0,0)
		_Main3rdDistanceFade ("", Vector) = (0.1,0.01,0,0)
		_AlphaMaskMode ("", Float) = 0
		_AlphaMask ("", 2D) = "white" {}
		_AlphaMaskScale ("", Float) = 1
		_AlphaMaskValue ("", Float) = 0
		_UseBumpMap ("", Float) = 0
		[Normal] _BumpMap ("", 2D) = "bump" {}
		_BumpScale ("", Range(-10, 10)) = 1
		_UseBump2ndMap ("", Float) = 0
		[Normal] _Bump2ndMap ("", 2D) = "bump" {}
		_Bump2ndMap_UVMode ("", Float) = 0
		_Bump2ndScale ("", Range(-10, 10)) = 1
		_Bump2ndScaleMask ("", 2D) = "white" {}
		_UseAnisotropy ("", Float) = 0
		[Normal] _AnisotropyTangentMap ("", 2D) = "bump" {}
		_AnisotropyScale ("", Range(-1, 1)) = 1
		_AnisotropyScaleMask ("", 2D) = "white" {}
		_AnisotropyTangentWidth ("", Range(0, 10)) = 1
		_AnisotropyBitangentWidth ("", Range(0, 10)) = 1
		_AnisotropyShift ("", Range(-10, 10)) = 0
		_AnisotropyShiftNoiseScale ("", Range(-1, 1)) = 0
		_AnisotropySpecularStrength ("", Range(0, 10)) = 1
		_Anisotropy2ndTangentWidth ("", Range(0, 10)) = 1
		_Anisotropy2ndBitangentWidth ("", Range(0, 10)) = 1
		_Anisotropy2ndShift ("", Range(-10, 10)) = 0
		_Anisotropy2ndShiftNoiseScale ("", Range(-1, 1)) = 0
		_Anisotropy2ndSpecularStrength ("", Range(0, 10)) = 0
		_AnisotropyShiftNoiseMask ("", 2D) = "white" {}
		_Anisotropy2Reflection ("", Float) = 0
		_Anisotropy2MatCap ("", Float) = 0
		_Anisotropy2MatCap2nd ("", Float) = 0
		_UseBacklight ("", Float) = 0
		_BacklightColor ("", Vector) = (0.85,0.8,0.7,1)
		_BacklightColorTex ("", 2D) = "white" {}
		_BacklightMainStrength ("", Range(0, 1)) = 0
		_BacklightNormalStrength ("", Range(0, 1)) = 1
		_BacklightBorder ("", Range(0, 1)) = 0.35
		_BacklightBlur ("", Range(0, 1)) = 0.05
		_BacklightDirectivity ("", Float) = 5
		_BacklightViewStrength ("", Range(0, 1)) = 1
		_BacklightReceiveShadow ("", Float) = 1
		_BacklightBackfaceMask ("", Float) = 1
		_UseShadow ("", Float) = 0
		_ShadowStrength ("", Range(0, 1)) = 1
		_ShadowStrengthMask ("", 2D) = "white" {}
		_ShadowStrengthMaskLOD ("", Range(0, 1)) = 0
		_ShadowBorderMask ("", 2D) = "white" {}
		_ShadowBorderMaskLOD ("", Range(0, 1)) = 0
		_ShadowBlurMask ("", 2D) = "white" {}
		_ShadowBlurMaskLOD ("", Range(0, 1)) = 0
		_ShadowAOShift ("", Vector) = (1,0,1,0)
		_ShadowAOShift2 ("", Vector) = (1,0,1,0)
		_ShadowPostAO ("", Float) = 0
		_ShadowColorType ("", Float) = 0
		_ShadowColor ("", Vector) = (0.82,0.76,0.85,1)
		_ShadowColorTex ("", 2D) = "black" {}
		_ShadowNormalStrength ("", Range(0, 1)) = 1
		_ShadowBorder ("", Range(0, 1)) = 0.5
		_ShadowBlur ("", Range(0, 1)) = 0.1
		_ShadowReceive ("", Range(0, 1)) = 0
		_Shadow2ndColor ("", Vector) = (0.68,0.66,0.79,1)
		_Shadow2ndColorTex ("", 2D) = "black" {}
		_Shadow2ndNormalStrength ("", Range(0, 1)) = 1
		_Shadow2ndBorder ("", Range(0, 1)) = 0.15
		_Shadow2ndBlur ("", Range(0, 1)) = 0.1
		_Shadow2ndReceive ("", Range(0, 1)) = 0
		_Shadow3rdColor ("", Vector) = (0,0,0,0)
		_Shadow3rdColorTex ("", 2D) = "black" {}
		_Shadow3rdNormalStrength ("", Range(0, 1)) = 1
		_Shadow3rdBorder ("", Range(0, 1)) = 0.25
		_Shadow3rdBlur ("", Range(0, 1)) = 0.1
		_Shadow3rdReceive ("", Range(0, 1)) = 0
		_ShadowBorderColor ("", Vector) = (1,0.1,0,1)
		_ShadowBorderRange ("", Range(0, 1)) = 0.08
		_ShadowMainStrength ("", Range(0, 1)) = 0
		_ShadowEnvStrength ("", Range(0, 1)) = 0
		_ShadowMaskType ("", Float) = 0
		_ShadowFlatBorder ("", Range(-2, 2)) = 1
		_ShadowFlatBlur ("", Range(0.001, 2)) = 1
		_UseRimShade ("", Float) = 0
		_RimShadeColor ("", Vector) = (0.5,0.5,0.5,1)
		_RimShadeMask ("", 2D) = "white" {}
		_RimShadeNormalStrength ("", Range(0, 1)) = 1
		_RimShadeBorder ("", Range(0, 1)) = 0.5
		_RimShadeBlur ("", Range(0, 1)) = 1
		_RimShadeFresnelPower ("", Range(0.01, 50)) = 1
		_UseReflection ("", Float) = 0
		_Smoothness ("", Range(0, 1)) = 1
		_SmoothnessTex ("", 2D) = "white" {}
		[Gamma] _Metallic ("", Range(0, 1)) = 0
		_MetallicGlossMap ("", 2D) = "white" {}
		[Gamma] _Reflectance ("", Range(0, 1)) = 0.04
		_GSAAStrength ("", Range(0, 1)) = 0
		_ApplySpecular ("", Float) = 1
		_ApplySpecularFA ("", Float) = 1
		_SpecularToon ("", Float) = 1
		_SpecularNormalStrength ("", Range(0, 1)) = 1
		_SpecularBorder ("", Range(0, 1)) = 0.5
		_SpecularBlur ("", Range(0, 1)) = 0
		_ApplyReflection ("", Float) = 0
		_ReflectionNormalStrength ("", Range(0, 1)) = 1
		_ReflectionColor ("", Vector) = (1,1,1,1)
		_ReflectionColorTex ("", 2D) = "white" {}
		_ReflectionApplyTransparency ("", Float) = 1
		_ReflectionCubeTex ("", Cube) = "black" {}
		_ReflectionCubeColor ("", Vector) = (0,0,0,1)
		_ReflectionCubeOverride ("", Float) = 0
		_ReflectionCubeEnableLighting ("", Range(0, 1)) = 1
		_ReflectionBlendMode ("", Float) = 1
		_UseMatCap ("", Float) = 0
		_MatCapColor ("", Vector) = (1,1,1,1)
		_MatCapTex ("", 2D) = "white" {}
		_MatCapMainStrength ("", Range(0, 1)) = 0
		_MatCapBlendUV1 ("", Vector) = (0,0,0,0)
		_MatCapZRotCancel ("", Float) = 1
		_MatCapPerspective ("", Float) = 1
		_MatCapVRParallaxStrength ("", Range(0, 1)) = 1
		_MatCapBlend ("", Range(0, 1)) = 1
		_MatCapBlendMask ("", 2D) = "white" {}
		_MatCapEnableLighting ("", Range(0, 1)) = 1
		_MatCapShadowMask ("", Range(0, 1)) = 0
		_MatCapBackfaceMask ("", Float) = 0
		_MatCapLod ("", Range(0, 10)) = 0
		_MatCapBlendMode ("", Float) = 1
		_MatCapApplyTransparency ("", Float) = 1
		_MatCapNormalStrength ("", Range(0, 1)) = 1
		_MatCapCustomNormal ("", Float) = 0
		[Normal] _MatCapBumpMap ("", 2D) = "bump" {}
		_MatCapBumpScale ("", Range(-10, 10)) = 1
		_UseMatCap2nd ("", Float) = 0
		_MatCap2ndColor ("", Vector) = (1,1,1,1)
		_MatCap2ndTex ("", 2D) = "white" {}
		_MatCap2ndMainStrength ("", Range(0, 1)) = 0
		_MatCap2ndBlendUV1 ("", Vector) = (0,0,0,0)
		_MatCap2ndZRotCancel ("", Float) = 1
		_MatCap2ndPerspective ("", Float) = 1
		_MatCap2ndVRParallaxStrength ("", Range(0, 1)) = 1
		_MatCap2ndBlend ("", Range(0, 1)) = 1
		_MatCap2ndBlendMask ("", 2D) = "white" {}
		_MatCap2ndEnableLighting ("", Range(0, 1)) = 1
		_MatCap2ndShadowMask ("", Range(0, 1)) = 0
		_MatCap2ndBackfaceMask ("", Float) = 0
		_MatCap2ndLod ("", Range(0, 10)) = 0
		_MatCap2ndBlendMode ("", Float) = 1
		_MatCap2ndApplyTransparency ("", Float) = 1
		_MatCap2ndNormalStrength ("", Range(0, 1)) = 1
		_MatCap2ndCustomNormal ("", Float) = 0
		[Normal] _MatCap2ndBumpMap ("", 2D) = "bump" {}
		_MatCap2ndBumpScale ("", Range(-10, 10)) = 1
		_UseRim ("", Float) = 0
		_RimColor ("", Vector) = (0.66,0.5,0.48,1)
		_RimColorTex ("", 2D) = "white" {}
		_RimMainStrength ("", Range(0, 1)) = 0
		_RimNormalStrength ("", Range(0, 1)) = 1
		_RimBorder ("", Range(0, 1)) = 0.5
		_RimBlur ("", Range(0, 1)) = 0.65
		_RimFresnelPower ("", Range(0.01, 50)) = 3.5
		_RimEnableLighting ("", Range(0, 1)) = 1
		_RimShadowMask ("", Range(0, 1)) = 0.5
		_RimBackfaceMask ("", Float) = 1
		_RimVRParallaxStrength ("", Range(0, 1)) = 1
		_RimApplyTransparency ("", Float) = 1
		_RimDirStrength ("", Range(0, 1)) = 0
		_RimDirRange ("", Range(-1, 1)) = 0
		_RimIndirRange ("", Range(-1, 1)) = 0
		_RimIndirColor ("", Vector) = (1,1,1,1)
		_RimIndirBorder ("", Range(0, 1)) = 0.5
		_RimIndirBlur ("", Range(0, 1)) = 0.1
		_RimBlendMode ("", Float) = 1
		_UseGlitter ("", Float) = 0
		_GlitterUVMode ("", Float) = 0
		_GlitterColor ("", Vector) = (1,1,1,1)
		_GlitterColorTex ("", 2D) = "white" {}
		_GlitterColorTex_UVMode ("", Float) = 0
		_GlitterMainStrength ("", Range(0, 1)) = 0
		_GlitterNormalStrength ("", Range(0, 1)) = 1
		_GlitterScaleRandomize ("", Range(0, 1)) = 0
		_GlitterApplyShape ("", Float) = 0
		_GlitterShapeTex ("", 2D) = "white" {}
		_GlitterAtras ("", Vector) = (1,1,0,0)
		_GlitterAngleRandomize ("", Float) = 0
		_GlitterParams1 ("", Vector) = (256,256,0.16,50)
		_GlitterParams2 ("", Vector) = (0.25,0,0,0)
		_GlitterPostContrast ("", Float) = 1
		_GlitterSensitivity ("", Float) = 0.25
		_GlitterEnableLighting ("", Range(0, 1)) = 1
		_GlitterShadowMask ("", Range(0, 1)) = 0
		_GlitterBackfaceMask ("", Float) = 0
		_GlitterApplyTransparency ("", Float) = 1
		_GlitterVRParallaxStrength ("", Range(0, 1)) = 0
		_UseEmission ("", Float) = 0
		[HDR] _EmissionColor ("", Vector) = (1,1,1,1)
		_EmissionMap ("", 2D) = "white" {}
		_EmissionMap_ScrollRotate ("", Vector) = (0,0,0,0)
		_EmissionMap_UVMode ("", Float) = 0
		_EmissionMainStrength ("", Range(0, 1)) = 0
		_EmissionBlend ("", Range(0, 1)) = 1
		_EmissionBlendMask ("", 2D) = "white" {}
		_EmissionBlendMask_ScrollRotate ("", Vector) = (0,0,0,0)
		_EmissionBlendMode ("", Float) = 1
		_EmissionBlink ("", Vector) = (0,0,3.141593,0)
		_EmissionUseGrad ("", Float) = 0
		_EmissionGradTex ("", 2D) = "white" {}
		_EmissionGradSpeed ("", Float) = 1
		_EmissionParallaxDepth ("", Float) = 0
		_EmissionFluorescence ("", Range(0, 1)) = 0
		_egci ("", Float) = 2
		_egai ("", Float) = 2
		_egc0 ("", Vector) = (1,1,1,0)
		_egc1 ("", Vector) = (1,1,1,1)
		_egc2 ("", Vector) = (1,1,1,0)
		_egc3 ("", Vector) = (1,1,1,0)
		_egc4 ("", Vector) = (1,1,1,0)
		_egc5 ("", Vector) = (1,1,1,0)
		_egc6 ("", Vector) = (1,1,1,0)
		_egc7 ("", Vector) = (1,1,1,0)
		_ega0 ("", Vector) = (1,0,0,0)
		_ega1 ("", Vector) = (1,0,0,1)
		_ega2 ("", Vector) = (1,0,0,0)
		_ega3 ("", Vector) = (1,0,0,0)
		_ega4 ("", Vector) = (1,0,0,0)
		_ega5 ("", Vector) = (1,0,0,0)
		_ega6 ("", Vector) = (1,0,0,0)
		_ega7 ("", Vector) = (1,0,0,0)
		_UseEmission2nd ("", Float) = 0
		[HDR] _Emission2ndColor ("", Vector) = (1,1,1,1)
		_Emission2ndMap ("", 2D) = "white" {}
		_Emission2ndMap_ScrollRotate ("", Vector) = (0,0,0,0)
		_Emission2ndMap_UVMode ("", Float) = 0
		_Emission2ndMainStrength ("", Range(0, 1)) = 0
		_Emission2ndBlend ("", Range(0, 1)) = 1
		_Emission2ndBlendMask ("", 2D) = "white" {}
		_Emission2ndBlendMask_ScrollRotate ("", Vector) = (0,0,0,0)
		_Emission2ndBlendMode ("", Float) = 1
		_Emission2ndBlink ("", Vector) = (0,0,3.141593,0)
		_Emission2ndUseGrad ("", Float) = 0
		_Emission2ndGradTex ("", 2D) = "white" {}
		_Emission2ndGradSpeed ("", Float) = 1
		_Emission2ndParallaxDepth ("", Float) = 0
		_Emission2ndFluorescence ("", Range(0, 1)) = 0
		_e2gci ("", Float) = 2
		_e2gai ("", Float) = 2
		_e2gc0 ("", Vector) = (1,1,1,0)
		_e2gc1 ("", Vector) = (1,1,1,1)
		_e2gc2 ("", Vector) = (1,1,1,0)
		_e2gc3 ("", Vector) = (1,1,1,0)
		_e2gc4 ("", Vector) = (1,1,1,0)
		_e2gc5 ("", Vector) = (1,1,1,0)
		_e2gc6 ("", Vector) = (1,1,1,0)
		_e2gc7 ("", Vector) = (1,1,1,0)
		_e2ga0 ("", Vector) = (1,0,0,0)
		_e2ga1 ("", Vector) = (1,0,0,1)
		_e2ga2 ("", Vector) = (1,0,0,0)
		_e2ga3 ("", Vector) = (1,0,0,0)
		_e2ga4 ("", Vector) = (1,0,0,0)
		_e2ga5 ("", Vector) = (1,0,0,0)
		_e2ga6 ("", Vector) = (1,0,0,0)
		_e2ga7 ("", Vector) = (1,0,0,0)
		_UseParallax ("", Float) = 0
		_UsePOM ("", Float) = 0
		_ParallaxMap ("", 2D) = "gray" {}
		_Parallax ("", Float) = 0.02
		_ParallaxOffset ("", Float) = 0.5
		_DistanceFadeColor ("", Vector) = (0,0,0,1)
		_DistanceFade ("", Vector) = (0.1,0.01,0,0)
		_DistanceFadeMode ("", Float) = 0
		_DistanceFadeRimColor ("", Vector) = (0,0,0,0)
		_DistanceFadeRimFresnelPower ("", Range(0.01, 50)) = 5
		_UseAudioLink ("", Float) = 0
		_AudioLinkDefaultValue ("", Vector) = (0,0,2,0.75)
		_AudioLinkUVMode ("", Float) = 1
		_AudioLinkUVParams ("", Vector) = (0.25,0,0,0.125)
		_AudioLinkStart ("", Vector) = (0,0,0,0)
		_AudioLinkMask ("", 2D) = "blue" {}
		_AudioLinkMask_ScrollRotate ("", Vector) = (0,0,0,0)
		_AudioLinkMask_UVMode ("", Float) = 0
		_AudioLink2Main2nd ("", Float) = 0
		_AudioLink2Main3rd ("", Float) = 0
		_AudioLink2Emission ("", Float) = 0
		_AudioLink2EmissionGrad ("", Float) = 0
		_AudioLink2Emission2nd ("", Float) = 0
		_AudioLink2Emission2ndGrad ("", Float) = 0
		_AudioLink2Vertex ("", Float) = 0
		_AudioLinkVertexUVMode ("", Float) = 1
		_AudioLinkVertexUVParams ("", Vector) = (0.25,0,0,0.125)
		_AudioLinkVertexStart ("", Vector) = (0,0,0,0)
		_AudioLinkVertexStrength ("", Vector) = (0,0,0,1)
		_AudioLinkAsLocal ("", Float) = 0
		_AudioLinkLocalMap ("", 2D) = "black" {}
		_AudioLinkLocalMapParams ("", Vector) = (120,1,0,0)
		_DissolveMask ("", 2D) = "white" {}
		_DissolveNoiseMask ("", 2D) = "gray" {}
		_DissolveNoiseMask_ScrollRotate ("", Vector) = (0,0,0,0)
		_DissolveNoiseStrength ("", Float) = 0.1
		_DissolveColor ("", Vector) = (1,1,1,1)
		_DissolveParams ("", Vector) = (0,0,0.5,0.1)
		_DissolvePos ("", Vector) = (0,0,0,0)
		[ToggleUI] _IDMaskCompile ("", Float) = 0
		_IDMaskFrom ("", Float) = 8
		[ToggleUI] _IDMask1 ("", Float) = 0
		[ToggleUI] _IDMask2 ("", Float) = 0
		[ToggleUI] _IDMask3 ("", Float) = 0
		[ToggleUI] _IDMask4 ("", Float) = 0
		[ToggleUI] _IDMask5 ("", Float) = 0
		[ToggleUI] _IDMask6 ("", Float) = 0
		[ToggleUI] _IDMask7 ("", Float) = 0
		[ToggleUI] _IDMask8 ("", Float) = 0
		[ToggleUI] _IDMaskIsBitmap ("", Float) = 0
		_IDMaskIndex1 ("", Float) = 0
		_IDMaskIndex2 ("", Float) = 0
		_IDMaskIndex3 ("", Float) = 0
		_IDMaskIndex4 ("", Float) = 0
		_IDMaskIndex5 ("", Float) = 0
		_IDMaskIndex6 ("", Float) = 0
		_IDMaskIndex7 ("", Float) = 0
		_IDMaskIndex8 ("", Float) = 0
		[ToggleUI] _IDMaskControlsDissolve ("", Float) = 0
		[ToggleUI] _IDMaskPrior1 ("", Float) = 0
		[ToggleUI] _IDMaskPrior2 ("", Float) = 0
		[ToggleUI] _IDMaskPrior3 ("", Float) = 0
		[ToggleUI] _IDMaskPrior4 ("", Float) = 0
		[ToggleUI] _IDMaskPrior5 ("", Float) = 0
		[ToggleUI] _IDMaskPrior6 ("", Float) = 0
		[ToggleUI] _IDMaskPrior7 ("", Float) = 0
		[ToggleUI] _IDMaskPrior8 ("", Float) = 0
		_UDIMDiscardCompile ("", Float) = 0
		_UDIMDiscardUV ("", Float) = 0
		_UDIMDiscardMode ("", Float) = 0
		_UDIMDiscardRow3_3 ("", Float) = 0
		_UDIMDiscardRow3_2 ("", Float) = 0
		_UDIMDiscardRow3_1 ("", Float) = 0
		_UDIMDiscardRow3_0 ("", Float) = 0
		_UDIMDiscardRow2_3 ("", Float) = 0
		_UDIMDiscardRow2_2 ("", Float) = 0
		_UDIMDiscardRow2_1 ("", Float) = 0
		_UDIMDiscardRow2_0 ("", Float) = 0
		_UDIMDiscardRow1_3 ("", Float) = 0
		_UDIMDiscardRow1_2 ("", Float) = 0
		_UDIMDiscardRow1_1 ("", Float) = 0
		_UDIMDiscardRow1_0 ("", Float) = 0
		_UDIMDiscardRow0_3 ("", Float) = 0
		_UDIMDiscardRow0_2 ("", Float) = 0
		_UDIMDiscardRow0_1 ("", Float) = 0
		_UDIMDiscardRow0_0 ("", Float) = 0
		_OutlineColor ("", Vector) = (0.6,0.56,0.73,1)
		_OutlineTex ("", 2D) = "white" {}
		_OutlineTex_ScrollRotate ("", Vector) = (0,0,0,0)
		_OutlineTexHSVG ("", Vector) = (0,1,1,1)
		_OutlineLitColor ("", Vector) = (1,0.2,0,0)
		_OutlineLitApplyTex ("", Float) = 0
		_OutlineLitScale ("", Float) = 10
		_OutlineLitOffset ("", Float) = -8
		_OutlineLitShadowReceive ("", Float) = 0
		_OutlineWidth ("", Range(0, 1)) = 0.08
		_OutlineWidthMask ("", 2D) = "white" {}
		_OutlineFixWidth ("", Range(0, 1)) = 0.5
		_OutlineVertexR2Width ("", Float) = 0
		_OutlineDeleteMesh ("", Float) = 0
		[Normal] _OutlineVectorTex ("", 2D) = "bump" {}
		_OutlineVectorUVMode ("", Float) = 0
		_OutlineVectorScale ("", Range(-10, 10)) = 1
		_OutlineEnableLighting ("", Range(0, 1)) = 1
		_OutlineZBias ("", Float) = 0
		_OutlineDisableInVR ("", Float) = 0
		_TessEdge ("", Range(1, 100)) = 10
		_TessStrength ("", Range(0, 1)) = 0.5
		_TessShrink ("", Range(0, 1)) = 0
		_TessFactorMax ("", Range(1, 8)) = 3
		_UseOutline ("", Float) = 0
		_TransparentMode ("", Float) = 0
		_UseClippingCanceller ("", Float) = 0
		_AsOverlay ("", Float) = 0
		_BaseColor ("", Vector) = (1,1,1,1)
		_BaseMap ("", 2D) = "white" {}
		_BaseColorMap ("", 2D) = "white" {}
		_lilToonVersion ("", Float) = 0
		_Ramp ("", 2D) = "white" {}
		_Cull ("", Float) = 2
		_SrcBlend ("", Float) = 1
		_DstBlend ("", Float) = 0
		_SrcBlendAlpha ("", Float) = 1
		_DstBlendAlpha ("", Float) = 10
		_BlendOp ("", Float) = 0
		_BlendOpAlpha ("", Float) = 0
		_SrcBlendFA ("", Float) = 1
		_DstBlendFA ("", Float) = 1
		_SrcBlendAlphaFA ("", Float) = 0
		_DstBlendAlphaFA ("", Float) = 1
		_BlendOpFA ("", Float) = 4
		_BlendOpAlphaFA ("", Float) = 4
		_ZClip ("", Float) = 1
		_ZWrite ("", Float) = 1
		_ZTest ("", Float) = 4
		_StencilRef ("", Range(0, 255)) = 0
		_StencilReadMask ("", Range(0, 255)) = 255
		_StencilWriteMask ("", Range(0, 255)) = 255
		_StencilComp ("", Float) = 8
		_StencilPass ("", Float) = 0
		_StencilFail ("", Float) = 0
		_StencilZFail ("", Float) = 0
		_OffsetFactor ("", Float) = 0
		_OffsetUnits ("", Float) = 0
		_ColorMask ("", Float) = 15
		_AlphaToMask ("", Float) = 0
		_lilShadowCasterBias ("", Float) = 0
		_OutlineCull ("", Float) = 1
		_OutlineSrcBlend ("", Float) = 1
		_OutlineDstBlend ("", Float) = 0
		_OutlineSrcBlendAlpha ("", Float) = 1
		_OutlineDstBlendAlpha ("", Float) = 10
		_OutlineBlendOp ("", Float) = 0
		_OutlineBlendOpAlpha ("", Float) = 0
		_OutlineSrcBlendFA ("", Float) = 1
		_OutlineDstBlendFA ("", Float) = 1
		_OutlineSrcBlendAlphaFA ("", Float) = 0
		_OutlineDstBlendAlphaFA ("", Float) = 1
		_OutlineBlendOpFA ("", Float) = 4
		_OutlineBlendOpAlphaFA ("", Float) = 4
		_OutlineZClip ("", Float) = 1
		_OutlineZWrite ("", Float) = 1
		_OutlineZTest ("", Float) = 2
		_OutlineStencilRef ("", Range(0, 255)) = 0
		_OutlineStencilReadMask ("", Range(0, 255)) = 255
		_OutlineStencilWriteMask ("", Range(0, 255)) = 255
		_OutlineStencilComp ("", Float) = 8
		_OutlineStencilPass ("", Float) = 0
		_OutlineStencilFail ("", Float) = 0
		_OutlineStencilZFail ("", Float) = 0
		_OutlineOffsetFactor ("", Float) = 0
		_OutlineOffsetUnits ("", Float) = 0
		_OutlineColorMask ("", Float) = 15
		_OutlineAlphaToMask ("", Float) = 0
		_SSAO ("", Float) = 0
		_SSAOStrength ("", Range(0, 5)) = 1
		_SSAORadius ("", Range(0.0001, 0.02)) = 0.005
		_SSAOSamples ("", Range(1, 10)) = 4
		_SSAODepthBias ("", Range(0, 0.2)) = 0.005
		_SSAOSpread ("", Range(0, 1)) = 0.5
		_SSAOJitter ("", Range(0, 1)) = 1
		_SSAONoiseType ("", Float) = 0
		_SSAONoiseSpace ("", Float) = 0
		_SSAOMultiBounce ("", Range(0, 1)) = 0
		_SSAOFOVAdjust ("", Float) = 0
		_SSAOFOV ("", Range(30, 120)) = 60
		_SSAOHideInShadow ("", Range(0, 1)) = 0
		_SSAOHideInLight ("", Range(0, 1)) = 0
		_SSAOBlendMode ("", Float) = 0
		[HDR] _SSAOColor ("", Vector) = (0,0,0,1)
		_SSAODistanceFadeMin ("", Float) = 3
		_SSAODistanceFadeMax ("", Float) = 5
		_SSAOMask ("", 2D) = "white" {}
		_SSAOInvertMask ("", Float) = 0
	}
	//DummyShaderTextExporter
	SubShader{
		Tags { "RenderType"="Opaque" }
		LOD 200

		Pass
		{
			HLSLPROGRAM
			#pragma vertex vert
			#pragma fragment frag

			float4x4 unity_ObjectToWorld;
			float4x4 unity_MatrixVP;
			float4 _MainTex_ST;

			struct Vertex_Stage_Input
			{
				float4 pos : POSITION;
				float2 uv : TEXCOORD0;
			};

			struct Vertex_Stage_Output
			{
				float2 uv : TEXCOORD0;
				float4 pos : SV_POSITION;
			};

			Vertex_Stage_Output vert(Vertex_Stage_Input input)
			{
				Vertex_Stage_Output output;
				output.uv = (input.uv.xy * _MainTex_ST.xy) + _MainTex_ST.zw;
				output.pos = mul(unity_MatrixVP, mul(unity_ObjectToWorld, input.pos));
				return output;
			}

			Texture2D<float4> _MainTex;
			SamplerState sampler_MainTex;
			float4 _Color;

			struct Fragment_Stage_Input
			{
				float2 uv : TEXCOORD0;
			};

			float4 frag(Fragment_Stage_Input input) : SV_TARGET
			{
				return _MainTex.Sample(sampler_MainTex, input.uv.xy) * _Color;
			}

			ENDHLSL
		}
	}
	Fallback "Unlit/Texture"
	//CustomEditor "lilToon.lilSSAOInspector"
}